name: ssh连接
on: push

jobs:
  ssh-connect:
    name: ssh-connect
    runs-on: ubuntu-latest
    steps:
      - name: Setup Debug Session
        uses: sui28456049/debugger-action@master

      - name: long limit setting
        run: |
          date && touch /tmp/keepalive
       