name: ssh连接
on: push

jobs:
  ssh-connect:
    name: ssh-connect
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      - name: Checkout Repo
        uses: actions/checkout@master
    
      - name: 
        uses: P3TERX/debugger-action@main

      - name: long limit setting
        run: |
          date && touch /tmp/keepalive
       