name: ssh连接
on: push

jobs:
  ssh-connect:
    name: ssh-connect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Debug Session
        uses: P3TERX/debugger-action@master
        run: |
          date && touch /tmp/keepalive
       